package az.edu.asoiu.entity;
// Generated May 25, 2017 2:55:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import javax.validation.constraints.NotNull;

/**
 * Indicator generated by hbm2java
 */
@Entity
@Table(name = "indicator", catalog = "diplom")
public class Indicator implements java.io.Serializable {

    private Long id;
    private String name;
    private Integer status;
    private Date dateCreated;
    private String icon;
    private String description;
    private Disease diseaseId;

    public Indicator() {
    }

    public Indicator(String name) {
        this.name = name;
    }

    public Indicator(String name, Integer status, Date dateCreated, String icon, String description, Disease diseaseId) {
        this.name = name;
        this.status = status;
        this.dateCreated = dateCreated;
        this.icon = icon;
        this.description = description;
        this.diseaseId = diseaseId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    @Column(name = "name", nullable = false, length = 1000)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_created", length = 19)
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }


    @Column(name = "icon", length = 16000)
    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }


    @Column(name = "description", length = 2500)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @NotNull
    @ManyToOne
    @JoinColumn(name = "disease_id", referencedColumnName = "id")
    public Disease getDiseaseId() {
        return diseaseId;
    }

    public void setDiseaseId(Disease diseaseId) {
        this.diseaseId = diseaseId;
    }
}


