package az.edu.asoiu.entity;
// Generated May 25, 2017 2:55:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * RelDiseaseIndicator generated by hbm2java
 */
@Entity
@Table(name = "rel_disease_indicator", catalog = "final_work")
public class RelDiseaseIndicator implements java.io.Serializable {

    private Long id;
    private Disease diseaseId;
    private Indicator indicatorId;
    private MedicalSolution medicalSolutionId;
    private MedicineSolutions medicineSolutionId;
    private Integer status;
    private Date dateCreated;
    private String note;

    public RelDiseaseIndicator() {
    }

    public RelDiseaseIndicator(Disease diseaseId, Indicator indicatorId, MedicalSolution medicalSolutionId, MedicineSolutions medicineSolutionId) {
        this.diseaseId = diseaseId;
        this.indicatorId = indicatorId;
        this.medicalSolutionId = medicalSolutionId;
        this.medicineSolutionId = medicineSolutionId;
    }

    public RelDiseaseIndicator(Disease diseaseId, Indicator indicatorId, MedicalSolution medicalSolutionId, MedicineSolutions medicineSolutionId, Integer status, Date dateCreated, String note) {
        this.diseaseId = diseaseId;
        this.indicatorId = indicatorId;
        this.medicalSolutionId = medicalSolutionId;
        this.medicineSolutionId = medicineSolutionId;
        this.status = status;
        this.dateCreated = dateCreated;
        this.note = note;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @ManyToOne
    @JoinColumn(name = "disease_id", referencedColumnName = "id")
    public Disease getDiseaseId() {
        return this.diseaseId;
    }

    public void setDiseaseId(Disease diseaseId) {
        this.diseaseId = diseaseId;
    }


    @NotNull
    @ManyToOne
    @JoinColumn(name = "indicator_id", referencedColumnName = "id")
    public Indicator getIndicatorId() {
        return this.indicatorId;
    }

    public void setIndicatorId(Indicator indicatorId) {
        this.indicatorId = indicatorId;
    }


    @NotNull
    @ManyToOne
    @JoinColumn(name = "medical_solution_id", referencedColumnName = "id")
    public MedicalSolution getMedicalSolutionId() {
        return this.medicalSolutionId;
    }

    public void setMedicalSolutionId(MedicalSolution medicalSolutionId) {
        this.medicalSolutionId = medicalSolutionId;
    }


    @NotNull
    @ManyToOne
    @JoinColumn(name = "medicine_solution_id", referencedColumnName = "id")
    public MedicineSolutions getMedicineSolutionId() {
        return this.medicineSolutionId;
    }

    public void setMedicineSolutionId(MedicineSolutions medicineSolutionId) {
        this.medicineSolutionId = medicineSolutionId;
    }


    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_created", length = 19)
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }


    @Column(name = "note", length = 1500)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }


}


